import { type NextPage } from "next";
import Head from "next/head";

const MetaTags: NextPage = () => {
  return (
    <>
        <Head>
            <title>MealMentor</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    </>
  );
};

export default MetaTags;
